#!/usr/bin/env python3
"""Generate proprietary-files.txt for the RK3576 common tree from a stock dump."""
import os
import re
import sys

SRC = "/home/tomin/devel/AmlogicKitchen/rk3576-m9s/level2"

# Files that LineageOS builds from source or that the device tree supplies.
EXCLUDE_EXACT = {
    "vendor/build.prop",
    "vendor/default.prop",
    "vendor/etc/NOTICE.xml.gz",
    "vendor/etc/fs_config_dirs",
    "vendor/etc/fs_config_files",
    "vendor/etc/group",
    "vendor/etc/passwd",
    "vendor/etc/cgroups.json",
    "vendor/etc/task_profiles.json",
    "vendor/etc/vintf/manifest.xml",
    "vendor/etc/vintf/compatibility_matrix.xml",
    "vendor/recovery-from-boot.p",
    # Generated by the build system from the VNDK/linker namespace config;
    # shipping the stock copy makes Make override its own build rule.
    "vendor/etc/linker.config.pb",
    # supplied by device/rockchip/rk3576-common/configs
    "vendor/etc/a2dp_audio_policy_configuration_7_0.xml",
    "vendor/etc/audio_effects.xml",
    "vendor/etc/audio_policy_configuration.xml",
    "vendor/etc/audio_policy_configuration_singlehal.xml",
    "vendor/etc/audio_policy_volumes_drc.xml",
    "vendor/etc/bluetooth_audio_policy_configuration_7_0.xml",
    "vendor/etc/default_volume_tables.xml",
    "vendor/etc/r_submix_audio_policy_configuration.xml",
    "vendor/etc/usb_audio_policy_configuration.xml",
    "vendor/etc/media_codecs.xml",
    "vendor/etc/media_codecs_c2_base.xml",
    "vendor/etc/media_codecs_google_c2.xml",
    "vendor/etc/media_codecs_performance.xml",
    "vendor/etc/media_profiles_V1_0.xml",
    "vendor/etc/HwComposerEnv.xml",
    "vendor/etc/display_settings.xml",
    "vendor/etc/package_uimode_config.xml",
    # CAS is dropped entirely: the stock service is just AOSP's
    # android.hardware.cas-service.example, which in Android 14 only ships
    # inside the com.android.hardware.cas APEX. Nothing replaces it.
    "vendor/bin/hw/android.hardware.cas-service.example",
    "vendor/etc/init/cas-default.rc",
    "vendor/etc/vintf/manifest/android.hardware.cas-service.xml",
    # ClearKey DRM comes from AOSP source instead (see rk3576.mk); it is an
    # ordinary installable vendor binary that brings its own .rc and VINTF
    # fragment, so the stock copies would collide.
    "vendor/bin/hw/android.hardware.drm-service.clearkey",
    "vendor/etc/init/android.hardware.drm-service.clearkey.rc",
    "vendor/etc/vintf/manifest/android.hardware.drm-service.clearkey.xml",
    # The ClearKey CAS plugin goes with the CAS service that was dropped above,
    # so nothing would load it. It is also unbuildable-adjacent: it links
    # libprotobuf-cpp-{full,lite}-21.7.so and this tree only carries 21.12.
    "vendor/lib/mediacas/libclearkeycasplugin.so",
    "vendor/lib64/mediacas/libclearkeycasplugin.so",
    # Declares android.hardware.sensors AIDL v2 ISensors/default, but the stock
    # ROM ships no implementation of it anywhere -- no vendor/bin/hw binary, no
    # library, no init .rc. A declared-but-absent AIDL HAL is worse than an
    # undeclared one: servicemanager keeps trying to lazy-start it, and
    # system_server's SensorDevice blocks forever, so the boot animation loops:
    #
    #   Could not find 'aidl/android.hardware.sensors.ISensors/default'
    #     for ctl.interface_start
    #   Service sensorservice didn't start. Returning NULL
    #
    # The framework compatibility matrix has sensors optional="true", and the
    # board's only sensor candidates (icm42607 accel/gyro) fail to probe in the
    # kernel anyway, so dropping the declaration is both safe and accurate.
    "vendor/etc/vintf/manifest/sensors-rockchip.xml",
    # android.hardware.bluetooth.audio-impl.so is dlopen'd by audiohalservice
    # (hardware/interfaces/audio/common/all-versions/default/service/service.cpp,
    # optionalInterfaceSharedLibs), so no DT_NEEDED sweep can see it -- yet the
    # stock manifest fragment below declares the HAL. Another declared-but-absent
    # case, reported as:
    #
    #   E audiohalservice: Failed to dlopen android.hardware.bluetooth.audio-impl.so
    #
    # We build AOSP's android.hardware.bluetooth.audio-impl instead (rk3576.mk),
    # which brings its own bluetooth_audio.xml, so the stock fragment must go or
    # the two collide on the same install path. The AOSP module also pulls in its
    # own libbluetooth_audio_session_aidl.so; keep the built one rather than the
    # blob, for the same reason.
    "vendor/etc/vintf/manifest/bluetooth_audio.xml",
    "vendor/lib/libbluetooth_audio_session_aidl.so",
    "vendor/lib64/libbluetooth_audio_session_aidl.so",
}

# --- Soong module name collisions with AOSP ---
# extract_utils turns vendor/etc/vintf/manifest/*.xml into prebuilt_etc_xml
# modules named after the file, and these four names also exist as AOSP
# modules, which is a hard "already defined by" build error. VINTF parses every
# file in the manifest directory regardless of its name, so extract them to a
# renamed destination ("src:dst" spec) and keep the stock services.
RENAME = {
    "vendor/etc/vintf/manifest/android.hardware.wifi.hostapd.xml":
        "vendor/etc/vintf/manifest/rk_wifi.hostapd.xml",
    "vendor/etc/vintf/manifest/android.hardware.wifi.supplicant.xml":
        "vendor/etc/vintf/manifest/rk_wifi.supplicant.xml",
}

EXCLUDE_PREFIX = (
    "vendor/etc/selinux/",       # built from sepolicy sources
    "vendor/etc/permissions/",   # copied from frameworks/native/data/etc
    "vendor/apex/",              # APEXes are rebuilt
    "vendor/lost+found",
    "vendor/odm/",               # symlink farm
    # 476 usb_modeswitch config files with no usb_modeswitch binary anywhere in
    # the ROM to consume them. Three of them ("12d1_#android", "12d1_#linux",
    # "19d2_#linux") also contain '#', which starts a comment in the generated
    # PRODUCT_COPY_FILES and breaks product config parsing outright.
    "vendor/etc/usb_modeswitch.d/",
)

# AOSP-built executables that must not be shadowed by prebuilts.
EXCLUDE_BINS = {
    "vendor/bin/abc", "vendor/bin/applypatch", "vendor/bin/awk",
    "vendor/bin/boringssl_self_test32", "vendor/bin/boringssl_self_test64",
    "vendor/bin/dumpsys", "vendor/bin/logwrapper", "vendor/bin/sh",
    "vendor/bin/toolbox", "vendor/bin/toybox_vendor", "vendor/bin/vndservice",
    "vendor/bin/vndservicemanager", "vendor/bin/wpa_cli",
    "vendor/bin/install-recovery.sh",
}
# NOTE: vendor/bin/hw/wpa_supplicant and hostapd are deliberately NOT excluded.
# The stock Wi-Fi stack is Rockchip's chip-multiplexing one (libwifi-hal.so ->
# libwifi-hal-aic/bcm/rtk/skw + librkwifi-ctrl), and AOSP has no wifi HAL for
# the AIC8800D80 on this board, so the whole stack is kept stock.

# Core AOSP / VNDK libraries: always rebuilt from source, never extracted.
AOSP_LIBS = {
    "libc", "libm", "libdl", "liblog", "libz", "libc++", "libc++_shared",
    "libbase", "libcutils", "libutils", "libhardware", "libhidlbase",
    "libhidlmemory", "libbinder", "libbinder_ndk", "libvndksupport",
    "libbacktrace", "libunwindstack", "liblzma", "libjsoncpp", "libtinyxml2",
    "libxml2", "libpcre2", "libselinux", "libcrypto", "libssl", "libsqlite",
    "libexpat", "libfmq", "libsync", "libnl", "libprocessgroup", "libsysutils",
    "libnetutils", "libminijail", "libavservices_minijail", "libcutils_sockets",
    "libadbconnection", "libdl_android", "libziparchive", "libasync_safe",
    "libsystem_properties", "libpackagelistparser", "libprocinfo",
    "libstagefright_foundation", "libstagefright_bufferpool@2.0",
    "libcodec2_vndk", "libcodec2_soft_common", "libsfplugin_ccodec_utils",
    "libion", "libdmabufheap", "libgralloctypes", "libui", "libnativewindow",
    "libnativebase", "libnativehelper", "libhwbinder", "libvintf",
    "libaudioutils", "libaudiofoundation", "libaudioroute", "libtinyalsa",
    "libtinycompress", "libeffectsconfig", "libmedia_helper", "libapexutil",
    "libvendorsupport", "libchrome", "libevent",
}

# Prefixes of AOSP-generated HAL interface libraries (android.hardware.*.so etc).
#
# These are skipped here and built from source instead -- see the big
# PRODUCT_PACKAGES block in rk3576.mk, which pins the exact frozen AIDL version
# each blob was compiled against. Building them beats extracting: AIDL versions
# are ABI-frozen so the result is equivalent, and for plain libraries it avoids
# pairing a stock library with a build-installed sibling from a different
# upstream drop (a stock libssl.so against the build's libcrypto.so, say).
AOSP_LIB_PREFIXES = (
    "android.hardware.", "android.hidl.", "android.frameworks.",
    "android.system.", "android.media.", "libclang_rt.", "libcodec2_hidl@",
    "libprotobuf-cpp", "libgrpc",
)

# Libraries that only *look* like AOSP interface libraries. Rockchip names some
# of its own implementations after the HAL they implement, and no amount of
# PRODUCT_PACKAGES will conjure those up -- they have to be extracted.
NOT_AOSP_LIBS = {
    "android.hardware.camera.provider-V1-external-impl-rk.so",
}

VENDOR_LIB_RE = re.compile(r"^vendor/lib(64)?/[^/]+$")


def is_aosp_lib(base):
    if not base.endswith(".so"):
        return False
    if base in NOT_AOSP_LIBS:
        return False
    stem = base[:-3]
    # strip a trailing @version (e.g. libfoo@1.0.so)
    if stem in AOSP_LIBS:
        return True
    if stem.split("@")[0] in AOSP_LIBS:
        return True
    return base.startswith(AOSP_LIB_PREFIXES)


def is_excluded(path):
    if path in EXCLUDE_EXACT or path in EXCLUDE_BINS:
        return True
    if path.startswith(EXCLUDE_PREFIX):
        return True
    if VENDOR_LIB_RE.match(path) and is_aosp_lib(os.path.basename(path)):
        return True
    return False


def collect():
    files = []
    for root, _dirs, names in os.walk(os.path.join(SRC, "vendor")):
        for n in names:
            full = os.path.join(root, n)
            if os.path.islink(full):
                continue
            rel = os.path.relpath(full, SRC)
            if not is_excluded(rel):
                files.append(rel)
    return sorted(files)


SECTIONS = [
    ("Audio", lambda p: "soundfx" in p or "audio" in p.lower()),
    ("Bluetooth", lambda p: "bluetooth" in p.lower() or "bt_" in p),
    ("Camera", lambda p: "camera" in p.lower() or "isp" in p.lower()
        or "aiq" in p.lower() or p.endswith("media-ctl") or p.endswith("v4l2-ctl")),
    ("DRM", lambda p: "mediadrm" in p or "mediacas" in p or "drm-service" in p
        or "widevine" in p.lower() or "cas" in os.path.basename(p).lower()),
    ("Firmware", lambda p: p.startswith("vendor/etc/firmware/")),
    ("GPU", lambda p: "mali" in p.lower() or "egl" in p or "vulkan" in p
        or "gpu" in p.lower()),
    ("Graphics / HWC", lambda p: "hwc" in p.lower() or "composer" in p.lower()
        or "allocator" in p.lower() or "mapper" in p.lower() or "gralloc" in p.lower()
        or "outputmanager" in p.lower() or "hw_output" in p or "rga" in p.lower()),
    ("Keylayouts", lambda p: p.startswith("vendor/usr/")),
    ("Media / MPP", lambda p: "mpp" in p.lower() or "rockit" in p.lower()
        or "codec2" in p.lower() or "media.c2" in p or "vpu" in p.lower()),
    ("NPU / RKNN models", lambda p: "rknn" in p.lower()),
    ("Picture quality", lambda p: "pq" in os.path.basename(p).lower()
        or "sculptor" in p.lower() or "vop_base" in p),
    ("TEE / Keymaster", lambda p: "optee" in p.lower() or "tee" in p.lower()
        or "keymaster" in p.lower() or "keymint" in p.lower()
        or "gatekeeper" in p.lower() or "weaver" in p.lower()
        or "rkp" in p.lower() or "hdcp" in p.lower()),
    ("USB", lambda p: "usb" in p.lower()),
    ("Wi-Fi", lambda p: "wifi" in p.lower() or "wpa" in p.lower()
        or "hostapd" in p.lower()),
]


def main():
    files = collect()
    assigned = {}
    for name, pred in SECTIONS:
        for f in files:
            if f in assigned:
                continue
            if pred(f):
                assigned[f] = name
    out = []
    out.append("## All blobs are from the stock H96 Max M9S firmware")
    out.append("## rk3576_a001_H96_Max_M9S_BTM_ATV-20250314.1513 (Android 14, SDK 34)")
    out.append("")
    def spec(f):
        """Emit "src:dst" when the destination must be renamed, else "src"."""
        dst = RENAME.get(f)
        return "%s:%s" % (f, dst) if dst else f

    for name, _ in SECTIONS:
        group = [f for f in files if assigned.get(f) == name]
        if not group:
            continue
        out.append("## %s" % name)
        out.extend(spec(f) for f in group)
        out.append("")
    rest = [f for f in files if f not in assigned]
    if rest:
        out.append("## Rockchip platform")
        out.extend(spec(f) for f in rest)
        out.append("")
    sys.stdout.write("\n".join(out))
    sys.stderr.write("total blobs: %d\n" % len(files))


if __name__ == "__main__":
    main()
